name : Claves Angelicae 
author : Gabriel Dunne, Cullen Miller
author_url : https://github.com/claves-angelicae
author_email : studio@gabrieldunne.com, cullen@pointlinesurface.com
markdown : redcarpet
mediaurl : http://media.quilime.com/ca/s
etherscan : https://etherscan.io
